Models/ErrorViewModel.cs
using System;

namespace SucsMembers.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
namespace SucsMembers.Models
{
    public class User {
        public int UserId {get;set;}
        public string GUID {get;set;}

        public string Username {get;set;}
        public string Firstname {get;set;}
        public string Lastname {get;set;}
        public ulong DiscordId {get;set;}
    }
    public class LoginModel {
        public string Username {get;set;}
        public string Password {get;set;}
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using SucsMembers.Models;
using SucsMembers.Database;

namespace SucsMembers.Controllers
{
    public class HomeController : Controller
    {
        private SMDbContext _context;

        public HomeController(SMDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Community()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using SucsMembers.Models;
using SucsMembers.Database;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;

namespace SucsMembers.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private SMDbContext _context;

        public UsersController(SMDbContext context)
        {
            _context = context;
        }
        [AllowAnonymous]
        public IActionResult Index() {
            if (HttpContext.User.Identity.IsAuthenticated){
              string username = HttpContext.User.Identity.Name;
              //Get the user with the same name as the cookie
              User user = _context.Users
                      .Where(u => u.Username == username)
                      .First();
              return View(user);
            }
            //Render Login.cshtml
            return View("Login");
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login([FromForm]LoginModel model)
        {
            User user = null;
            if (model.Username == null){
              //TODO replace with propper error handling
              user = _context.Users
                      .Where(u => u.Username == "whizzywig")
                      .First();
            }else{
              user = _context.Users
                      .Where(u => u.Username == model.Username)
                      .First();
            }
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Username),
                //If we want to add more claims
                //new Claim("FirstName", user.Firstname),
                //new Claim("LastName", user.Lastname),
            };

            var claimsIdentity = new ClaimsIdentity(
              claims, CookieAuthenticationDefaults.AuthenticationScheme);

              var authProperties = new AuthenticationProperties
              {
              //AllowRefresh = <bool>,
              // Refreshing the authentication session should be allowed.

              //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
              // The time at which the authentication ticket expires. A
              // value set here overrides the ExpireTimeSpan option of
              // CookieAuthenticationOptions set with AddCookie.

              //IsPersistent = true,
              // Whether the authentication session is persisted across
              // multiple requests. When used with cookies, controls
              // whether the cookie's lifetime is absolute (matching the
              // lifetime of the authentication ticket) or session-based.

              //IssuedUtc = <DateTimeOffset>,
              // The time at which the authentication ticket was issued.

              //RedirectUri = <string>
              // The full path or absolute URI to be used as an http
              // redirect response value.
            };
            //Gives the user their cookie
            await HttpContext.SignInAsync(
              CookieAuthenticationDefaults.AuthenticationScheme,
              new ClaimsPrincipal(claimsIdentity),
              authProperties);

            //return the user back to the profile page
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Logout(){
          await HttpContext.SignOutAsync();
          return RedirectToAction("Index");
        }
    }
}

Views/Home/Community.cshtml
@{
    ViewData["Title"] = "Community";
}

<div class="title">
    <p class="title-subtitle">The community page for Sucs</p>
    <p>Join the discord - or find members on milliways</p>
    <p>TODO</p>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="title">
    <p class="title-subtitle">Welcome the new landing page for the sucs hub</p>
    <h1 class="title-text">Upcoming Events</h1>
    <p>TODO</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SM</title>
    <link rel="stylesheet" href="~/lib/css/milligram.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Fira+Code&display=swap" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">Profile</a>
        <a href="https://sucs.org/index.php">Main Site</a>
        <a href="https://games.sucs.org">Games</a>
        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Community">Community</a>
        <a href="https://join.sucs.org">Join</a>
        @if(User.Identity.IsAuthenticated){
            <div>
                <p>
                Logged in as, @User.Identity.Name
                </p>
            </div>
        }
    </nav>
    <div class="container content">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            &copy; 2020 - SucsMembers
        </div>
    </footer>
    <script src="~/lib/js/jquery-3.4.1.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Users/Index.cshtml
@model SucsMembers.Models.User;
@{
    ViewData["Title"] = "Profile";
}


<div class="title">
    <h1 class="title-text">@Model.Firstname @Model.Lastname</h1>
    <p class="title-subtitle">@Model.Username :: @Model.GUID</p>
</div>
<ol>
    <li>Id :: @Model.GUID</li>
    <li>Username :: @Model.Username</li>
    @if(Model.DiscordId != 0){
        <li>Discord :: #@Model.DiscordId</li>
    }
</ol>
<a class="button" asp-controller="Users" asp-action="Logout">Logout</a>

Views/Users/Login.cshtml
@model SucsMembers.Models.LoginModel;

<form action="Users/Login" method="post">
    <div><label for="Username">Username</label></div>
    <div><input type="text" placeholder="username" id="Username" asp-for="Username"></div>
    <div><label for="Password">Password</label></div>
    <div><input type="password" id="Password" asp-for="Password"></div>
    <div><input class="primary-button" type="submit" value="Login" ></div>
</form>